[tool.poetry]
name = "mkdocs_experiement"
version = "0.1.0"
description = ""
authors = ["Knut H Pederseen <knuthp@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-material = "^7.3.6"
mkdocs = "^1.2.3"
mkdocstrings = "^0.16.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
flake8 = "^4.0.1"
isort = "^5.10.1"
black = "^21.10b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
