[project]
name = "mkdocs_experiement"
version = "0.1.0"
description = ""
authors = [
    { name = "Knut H Pederseen", email = "knuthp@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mkdocs-material>=9.7.6",
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=1.0.3",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.8"
]

# If this is not a package (same as poetry's package-mode = false)
[tool.uv]
package = false

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"